# .streamlit/secrets.toml
# These are your local Streamlit secrets.
# When you deploy to Streamlit Community Cloud, you will copy/paste this exact text into the Advanced Settings -> Secrets box.

KAGGLE_API_TOKEN = "KGAT_436914d28395aeaf4be23a46fe85dfeb"
